[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoincore-rpc = "0.19.0"
bitcoin = "0.32.6"
serde = "1.0"
serde_json = "1.0.141"
